# Configuración común para todos los servicios
# Tienda: aspdemoshorustech
# Este archivo contiene valores compartidos entre todos los charts

global:
  timezone: "America/Panama"
  companyId: 1
  imageRegistry: aspposlite.azurecr.io
  imageRepository: asptg.com/ierpposlite
  imageTag: stable  # stable, latest, unstable

# Configuración de recursos compartidos
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

# Storage class para volúmenes persistentes
persistence:
  storageClass: local-path
