replicas: 1
hostNetwork: true

config:
  tunnelId: ""
  credentialsFile: ""
  ingress:
    - hostname: <nombre-tienda>-9010.asptienda.com
      service: http://localhost:9010
    - hostname: <nombre-tienda>-9012.asptienda.com
      service: http://localhost:9012
    - hostname: <nombre-tienda>-9014.asptienda.com
      service: http://localhost:9014
    - hostname: <nombre-tienda>-9015.asptienda.com
      service: http://localhost:9015
    - hostname: <nombre-tienda>-9020.asptienda.com
      service: http://localhost:9020
    - hostname: <nombre-tienda>-9021.asptienda.com
      service: http://localhost:9021
    - hostname: <nombre-tienda>-5050.asptienda.com
      service: http://localhost:5050
    - hostname: <nombre-tienda>-5432.asptienda.com
      service: tcp://localhost:5432
    - service: http_status:404
