# Configuración específica para Core
# Este archivo se usa con el chart poslite-core

# Configuración de imágenes
imageTag: stable  # stable, latest, unstable

# Portal (hostPort: 10014)
portal:
  enabled: true
  replicas: 1

# WebAPI (hostPort: 10012)
webapi:
  enabled: true
  replicas: 1

# Configuración específica de Core
config:
  timezone: "America/Panama"
  companyId: 1
  coreApiKey: "TEST"
  ierpUrl: "http://ierpgateway.azurewebsites.net/"
