replicas: 1
hostNetwork: true

config:
  tunnelId: ""
  credentialsFile: ""
  ingress:
    - hostname: <nombre-tienda>-7012.asptienda.com
      service: http://localhost:7012
    - hostname: <nombre-tienda>-7014.asptienda.com
      service: http://localhost:7014
    - hostname: <nombre-tienda>-7010.asptienda.com
      service: http://localhost:7010
    - hostname: <nombre-tienda>-7015.asptienda.com
      service: http://localhost:7015
    - hostname: <nombre-tienda>-7016.asptienda.com
      service: http://localhost:7016
    - hostname: <nombre-tienda>-7020.asptienda.com
      service: http://localhost:7020
    - hostname: <nombre-tienda>-5050.asptienda.com
      service: http://localhost:5050
    - hostname: <nombre-tienda>-5432.asptienda.com
      service: tcp://localhost:5432
    - service: http_status:404
