replicas: 1
hostNetwork: true

config:
  tunnelId: ""
  credentialsFile: ""
  ingress:
    - hostname: <nombre-tienda>-10014.asptienda.com
      service: http://localhost:10014
    - hostname: <nombre-tienda>-10012.asptienda.com
      service: http://localhost:10012
    - hostname: <nombre-tienda>-5050.asptienda.com
      service: http://localhost:5050
    - hostname: <nombre-tienda>-5432.asptienda.com
      service: tcp://localhost:5432
    - service: http_status:404
