# Configuración específica para Core
# Este archivo se usa con el chart poslite-core

# Configuración de imágenes
imageTag: unstable  # stable, latest, unstable

# Portal
portal:
  enabled: true
  replicas: 1

# WebAPI
webapi:
  enabled: true
  replicas: 1

# Configuración específica de Core
config:
  timezone: "America/Panama"
  companyId: 1
  coreApiKey: "TEST"
  ierpUrl: "http://ierpgateway.azurewebsites.net/"
